config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'cocktails#home'
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def home
  end
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail_id: @cocktail.id)

  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktails_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktails_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new

    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredients = Ingredient.all
    @dose = Dose.new
    @dose.cocktail = @cocktail
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.delete
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :coctail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/home.html.erb
<p class="h2-text margin-top">WELCOME TO THE</p>
<p class="name">ALCOMIX</p>
<p class="h2-text">We’ve Got the Right Ingredients for Your Favorite Cocktail!</p>

app/views/cocktails/index.html.erb
<div class="list-container">
  <ul class="cocktail-list">
    <% @cocktails.each do |el|%>
      <li >
        <%= link_to "#{el.name}",  cocktail_path(el) %> <span>$99</span>
      </li>
    <% end %>
  </ul>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for (@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.submit "create a cocktail" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="main-info">
  <div class="photo">
    <h2 class="header"><%= @cocktail.name %></h2>
    <img src="https://images.unsplash.com/photo-1506802913710-40e2e66339c9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" alt="">
  </div>
  <div class="info-box">
    <div class="price-box">
      <p class="price">Price:$25</p>
    </div>
    <div class="price-box">
      <p>Portion Size</p>
      <p class="portion">300ml</p>
    </div>
    <div class="">
      <%= link_to "Delete", root_path, class: 'delete' %>
    </div>

  </div>
</div>
<div class="ingredients">
  <h2 class="header">Ingredients</h2>
  <%= link_to "Add Ingredients", new_cocktail_dose_path(@cocktail),  class: 'btn-create-dose' %>
  <div class="ingredient-list">
    <% if @doses.exists? %>
      <% @doses.each do |dose|%>
        <% @ingredient = Ingredient.where(id: dose.ingredient_id) %>
        <div class="ingredient-el">
          <p><%= @ingredient[0].name %></p>
          <p><%= dose.description %></p>
          <%= link_to 'Delete Dose', dose_path(dose), method: :delete %>
        </div>
      <% end %>
    <% else %>
      <p>No doses any doses and ingrediesnts yet</p>
    <% end %>
  </div>
</div>

app/views/doses/new.html.erb
<h2>
  <%= @cocktail.name %>
</h2>

<%= simple_form_for (@dose), url: (cocktail_doses_path) do |f|%>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit "click" %>
<% end %>

app/views/layouts/_container.html.erb
<div class="wrapper">
  <div class="my-container">
    <div class="nav-bar">
      <%= link_to root_path  do %>
        <%= image_tag "invert-logo.png" %>
      <% end %>
      <div class="navigation">

          <%= link_to "Home", root_path %>
          <%= link_to "Cocktails",  cocktails_path%>
          <%= link_to "Create Cocktail",  new_cocktail_path%>

      </div>
    </div>

app/views/layouts/_container_end.html.erb
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/container' %>
        <%= yield %>
      <%= render 'layouts/container_end' %>
  </body>
</html>